### ISSUE TITLE
Add memory component

### ISSUE THREAD

**Issue by J-E-Mc** [rust-motd/rust-motd#11]
Add a component similar to the filesystems component that displays current memory and swap usage

**Comment by aaronscode** [comment]
@J-E-Mc Sorry for taking so long with this. Please check out 8adbf1ab82a23efd22af982211ea27106e13bb65 and let us know if that works for you. There's config to allow the swap to be either displayed besides or below the RAM usage (or not at all). See the example config or README for more

**Comment by aaronscode** [comment]
Marking this as closed because it's been awhile, feel free to re-open if you encounter an issue.
