### ISSUE TITLE
Allow reordering components

### ISSUE THREAD

**Issue by MarcelRobitaille** [rust-motd/rust-motd#16]
Right now, the order in which the components are printed is hard coded. There should be a way to configure this. It would be nice for this to be the order that they appear in the `config.toml`, but serde doesn't seem to have a way to do this (at least when deserializing into a struct).

**Comment by NickLarsenNZ** [comment]
Just stumbled on this issue and had a couple of thoughts:

- One way could be to introduce an `index` attribute to each component.
- Another way that makes it ergonomic for the user could be do deserialize the config into a map that preserves ordering of the keys (keys being the components), enumerating that before serializing/deserializing into the current data structures but with an added `index` field that is based on the enumeration index (but without the user having to explicitly define it).

**Comment by MarcelRobitaille** [comment]
Hi @NickLarsenNZ. Thanks for your comment. I would like to avoid the first option if possible. The second option sounds good. Do you have an idea of how to implement it? I looked into something similar before but gave up.

**Comment by NickLarsenNZ** [comment]
I had a quick (well long) play tonight and got a little bit working. It is a little convoluted, at lease in one file. I'm not familiar with custom deserializers so I just followed an example until it started compiling.

Given this config: https://github.com/NickLarsenNZ/rust-motd/blob/51cb39efe32fb81c756e798bd4d321e04bbd62e6/examples/ordered_config.rs#L117-L128

It _remembers_ the order:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/10092581/174192580-ba2b9acc-da04-4207-9688-296727b4fb51.png">

I think if it implemented `Iterator` and `Display` it could be printed out in the order based on `position`. I haven't gone back to see how your code actually prints out the components. I'll try and come back to this.

**Comment by MarcelRobitaille** [comment]
Thank you so much @NickLarsenNZ. That looks great. Looks like theres some error cases to clean up, but it should be pretty easy to implement. I know the other author and I are pretty busy right now. You're welcome to make a pull request if you have the time, or we will get to it as soon as we can.

**Comment by NickLarsenNZ** [comment]
Thanks for taking a look.
I hope to spend some time in the weekend, so I'll update you when I have something. I think I can simplify it a bit now that I know a little more about the deserialisation process.

**Comment by MarcelRobitaille** [comment]
@NickLarsenNZ I understand completely. I'm also extremely busy right now.

**Comment by MarcelRobitaille** [comment]
@NickLarsenNZ Thanks for your help with this. I hope you don't mind, I used your code as a starting point for #26. You are welcome to contribute to that draft pull request if you wish.
