### ISSUE TITLE
Crash on "Last Login" component

### ISSUE THREAD

**Issue by simonwiles** [rust-motd/rust-motd#18]
Getting this issue with accounts with no logins on a version compiled from source on CentOS 7:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/components/last_login.rs:80:83
```

Any idea what might be wrong?

Edit: same issue when compiled from source on my Arch workstation; presumably related to 35a5c6f174911a006d5b581b9845f6ad125010a0.

**Comment by aaronscode** [comment]
Hey thanks for the heads up. The last_login component was recently re-written and there may have been a regression in that (which you correctly identified in your edit). Just to start the troubleshooting process, what does your config for the last_login component look like?

**Comment by simonwiles** [comment]
I can replicate just by creating a new user on my workstation and using this:
```
[last_login]
simon = 1
test = 1
```
Works as expected once `test` has logged in at least once.

Incidently compiling `v0.1.0` from source on CentOS 7 results in:
```
Last login error: "last" failed with exit code 1:
"last: invalid option -- '-'\nUsage: last [-num | -n num] [-f file] [-t YYYYMMDDHHMMSS] [-R] [-adioxFw] [username..] [tty..]\n"
```

but if the `last-rs` version can be fixed I suppose that's moot.

Thanks for looking!

**Comment by MarcelRobitaille** [comment]
Sorry that you're experiencing this issue.

Would you try a730e86 please?

> Incidently compiling v0.1.1 from source on CentOS 7 results in:

This should be fixed in recent versions. We don't parse `last` anymore, we read `/var/log/wtmp` directly.

**Comment by simonwiles** [comment]
Yep, that works great, thanks for the quick fix.

For context I've been passing in the output of:
```
USERS=( $(
  getent passwd \
  | grep -vE '(nologin|false)$' \
  | awk -F: -v min=$(awk '/^UID_MIN/ {print $2}' /etc/login.defs) -v max=$(awk '/^UID_MAX/ {print $2}' /etc/login.defs) '{if(($3 >= min)&&($3 <= max)) print $1}' \
  | sort -u
) )

printf '%s = 1\n' "${USERS[@]}";
```
So as to see all user accounts with valid login shells, which is why I have multiple accounts with no logins.

Would you like me to close this, or wait for this fix to be released?

**Comment by MarcelRobitaille** [comment]
Let's close it.

> Yep, that works great, thanks for the quick fix.

Glad you're using it!

> So as to see all user accounts with valid login shells, which is why I have multiple accounts with no logins.

Hm, if you'd like, we could add an option to show all users?

**Comment by simonwiles** [comment]
> Hm, if you'd like, we could add an option to show all users?

Well certainly that's my main use case (and I imagine I won't be alone).  I'm using a script to generate the config toml (it also adds all the `fail2ban` jails on the system so I don't need to specify them) and using it with `rust_motd <(./gen_rust_motd_toml.sh)` or similar, and it seems to be working well for me so far.

**Comment by MarcelRobitaille** [comment]
> If this is turning into a feature request grinning then I've love to see all the recent logins in order of recency (most recent last), perhaps with the option to exclude accounts that have never logged in.

I'll talk to the other author and see what we can do
