### ISSUE TITLE
time_format ignored

### ISSUE THREAD

**Issue by giorgiga** [rust-motd/rust-motd#19]
_This happens running the released binary, labelled as for arch, on fedora 35. Just delete this if you can't replicate._

_I did try to compile from source to make sure it's not a fedora vs arch issue, but the build fails (`process didn't exit successfully: [...]/rust-motd/target/debug/build/openssl-sys-c1f7400878379ac8/build-script-main`) and I can't be bothered figuring out how to fix it. Still, I thought it to report would be better than not to._

----

Running with the configuration:

```
[global]
time_format = "%Y-%m-%d %H:%M:%S"

[last_login]
your_user = 1

[last_run]
```
results in:
```
Last Login:
  your_user:
    from 0.0.0.0 at 01/02/2022 11:11AM (still logged in)

Last updated: 2022/01/02 09:55 pm
```
Where two different time formats are used, none of which matches the configured one (which is the same as to what the default should be),

**Comment by MarcelRobitaille** [comment]
The latest release is pretty old. I think we're overdue for a release. The time format is being respected for me in both places on main. I will see with the other author about making a release. I remember we were waiting for something, but I forget for what.

**Comment by giorgiga** [comment]
That's great. I've subscribed to new releases and will double check later. I guess we may close this
