### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by lotation** [rust-motd/rust-motd#2]
Hello,
When I try to run `rust-motd` I get this error:
```
Config Error: Configuration file not found.
Make a copy of default config and either specify it as an arg or
place it in a default location.  See ReadMe for details.
```
(`rust-motd` installed from AUR with `paru`)

I don't know where the config file is supposed to be plus I didn't read anything mentioning it in the ReadMe.
Thanks for your time.

**Comment by MarcelRobitaille** [comment]
Hi @lotation,

Yes, you need to place the configuration file in `~/.config/rust-motd/config.toml`. You can use the `default_config.toml` as an example. Sorry about the missing documentation. This is a side project and neither of use have had time to write that section.

**Comment by lotation** [comment]
> Hi @lotation,
> 
> Yes, you need to place the configuration file in `~/.config/rust-motd/config.toml`. You can use the `default_config.toml` as an example. Sorry about the missing documentation. This is a side project and neither of use have had time to write that section.

Thank you @MarcelRobitaille, don't worry about the missing informations your program is great.
