### ISSUE TITLE
Upgrade rust edition and out of date dependencies

### ISSUE THREAD

**Issue by NickLarsenNZ** [rust-motd/rust-motd#23]
I was wondering if I could raise a PR to update the rust edition and also some of the dependencies?

- Rust edition 2018 -> 2021
- itertools `0.8` -> `0.10`
- time `0.1.44` -> perhaps remove it in place of chrono? Otherwise `0.3.9` if it is still required?

I noticed I cannot build it with the old edition (as mentioned in my note on https://github.com/rust-motd/rust-motd/issues/16#issuecomment-1158246075), but maybe that is my toolchain setup?

```
❯ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/nick/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)

```

**Comment by MarcelRobitaille** [comment]
That's odd. It's compiling for me no problem. I don't have rustup installed. I am using cargo 0.61.0 (a028ae4 2022-04-29). It might be the toolchain stuff. We've also had reports that builds were failing on darwin (#20). Some of the libraries we use aren't fully supported. It should have been fixed now though.

I'd like to see what @aaronscode thinks of this when he has a chance before merging.

**Comment by NickLarsenNZ** [comment]
> I'd like to see what @aaronscode thinks of this when he has a chance before merging.

No problem, I'll leave the PR there anyway, but you're welcome to close it if it isn't desired. I'll checkout my toolchain in the meantime.

**Comment by NickLarsenNZ** [comment]
Hmm, I can't reproduce the error. I checked out `v0.2.1` and it is compiling fine (just some warnings). I swear I saw red, and recall some peculiar complaints. I have done a `cargo clean` (not sure if that could resolve it).

Sorry about that. Would you still like the updates in the PR?
