### ISSUE TITLE
`--help` flags result in error about missing config

### ISSUE THREAD

**Issue by montchr** [rust-motd/rust-motd#29]
Upon first installation via `nix profile install nixpkgs#rust-motd`:

```console
$ rust-motd --help
Config Error: No such file or directory (os error 2)
$ rust-motd -h
Config Error: No such file or directory (os error 2)
$ rust-motd help
Config Error: No such file or directory (os error 2)
```

I'm on `aarch64-darwin` if it makes a difference.

**Comment by MarcelRobitaille** [comment]
We don't have a help page. The usage is `rust-motd <config-file.toml>`. Or just `rust-motd` and it will look for the config file in normal places as described [here](https://github.com/rust-motd/rust-motd#configuration). 

We should consider adding a help page, but the usage is so simple we would have to set up a lot of boilerplate just to detect that one command
