### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by kusky3** [rust-motd/rust-motd#3]
error while running cargo build on the latest version

error[E0597]: `current_regex` does not live long enough
  --> src/components/fail_2_ban.rs:46:18

**Comment by MarcelRobitaille** [comment]
Cannot reproduce on `cargo 1.49.0 (d00d64df9 2020-12-05)`. Could you please specify your version?

**Comment by kusky3** [comment]
cargo 1.55.0 on armv7l

**Comment by MarcelRobitaille** [comment]
Thank you for your report. We will look into it.

**Comment by MarcelRobitaille** [comment]
Fixed in fc77515
